version: 1.0.-{build}
build:
  verbosity: minimal
before_build:
- cmd: dotnet restore
after_build:
- ps: dotnet build -c Release -o "..\output"
- ps: Get-ChildItem output -Recurse -Filter LastModifiedPostProcessor.dll | % { Push-AppveyorArtifact $_.FullName }