image: Visual Studio 2017
version: 1.1.1-{build}
build:
  verbosity: minimal
before_build:
- cmd: dotnet restore
after_build:
- ps: dotnet build -c Release -o "..\output"
- ps: Get-ChildItem output -Recurse -Filter DocFX.Plugin.DescriptionGenerator.dll | % { Push-AppveyorArtifact $_.FullName }